apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
        - name: oracle
          image: container-registry.oracle.com/database/free:latest
          ports:
            - containerPort: 1521
            - containerPort: 5500
          env:
            - name: ORACLE_PWD
              value: "Oracle2025"  # Works for both express and free images
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-storage
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - echo | sqlplus -L system/$ORACLE_PWD@//localhost:1521/FREEPDB1
            initialDelaySeconds: 90
            periodSeconds: 10
      volumes:
        - name: oracle-storage
          persistentVolumeClaim:
            claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  type: NodePort
  selector:
    app: oracle
  ports:
    - name: db-port
      port: 1521
      targetPort: 1521
      nodePort: 31521
    - name: web-port
      port: 5500
      targetPort: 5500
      nodePort: 32500
